### ISSUE TITLE
Web Interface is Vulnerable

### ISSUE THREAD

**Issue by il8677** [ISD-Sound-and-Lights/Inventory-Server#1]
There is a server folder on the actual repository, so this is obsolete. Also web interface vulnerable

**Comment by DyingEcho** [comment]
This has a frontend, so not obolete.

How is it vulnerable? There is next to nothing there yet, just the basics.

**Comment by il8677** [comment]
Check Slack

**Comment by DyingEcho** [comment]
Further developments may come only when the client is complete, but the main goal of this is to be a basic interface we can build on in the future.

All web interfaces are vulnerable. As are all servers. As are all local clients, if they do anything with the server. This will be no different. However, by securing it and making it available only within ISD the risk will be next to zero and definitely worth the benefit.
